Entity resolution search now returns all phone numbers
anidata/ht-archive pull request #11
Opened 2017-03-12 22:16 UTC by geezhawk

Used nested pg queries to get all entity phone numbers as a list, instead of just returning the phone number given in the query.

We'll want to refactor this into something that makes use of a library like [pg-promise](https://github.com/vitaly-t/pg-promise) at some point, since nested callbacks are kind of an antipattern.

Fixes #3

2017-03-14 01:44 UTC, dlrobertson requested changes
Looks good, but it looks like you missed a `console.log`. Have you ran and tested this locally?

2017-03-14 01:44 UTC, danlrobertson commented on routes/queries.js
> +        console.log(q);
Debug statement :)

2017-03-14 01:44 UTC, danlrobertson commented on routes/queries.js
> -            console.log(result.rows);
Thanks

2017-03-14 13:07 UTC, geezhawk commented
Whoops - I'll go ahead and strip out the console logs :). I have tested it locally.

2017-03-18 16:18 UTC, geezhawk commented
Removed the console log - let me know if there's anything else that needs to be changed

2017-03-26 21:19 UTC, dlrobertson approved these changes

2017-03-26 21:19 UTC, danlrobertson commented
Thanks for working on this!

2017-03-26 21:49 UTC, merged